FROAS/urls.py
from django.contrib import admin
from django.urls import path, include
from FROAS import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('users/', include('users.urls')),
    path('tau/', include('tau.urls')),
]

tau/urls.py
from django.urls import path
from . import views

app_name = 'tau'

urlpatterns = [
    path('<int:id>/upload', views.upload, name='upload'),
    path('<int:id>/list', views.list, name='list'),
    path('<int:id>/list_data', views.list_data, name='list_data'),
    path('<int:id>/class_history', views.class_history, name='class_history'),
    path('<int:id>/list_classes', views.list_classes, name='list_classes'),
    path('<int:id>/display', views.display, name='display'),
    
    path('<int:id>/create', views.create_class, name='create'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signin', views.signin, name='signin'),
    path('signout', views.signout, name='signout'),
    path('profiles/<int:id>', views.get_profile, name='get_profile'),
    path('profiles/<int:id>/edit', views.edit_profile, name='edit_profile'),
]

templates/about.html
{% extends 'basic.html' %}

{% block title %} About {% endblock %}

{% block body %} <h1>This is About Page</h1> {% endblock %}

templates/basic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">

    <link rel="stylesheet" href="{% static 'sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'profile.css' %}">
    <link rel="stylesheet" href="{% static 'list.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script type="text/javascript" charset="utf8"
        src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

    {% block css %} {% endblock %}

    <title>{% block title %} {% endblock %}</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">FROAS</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/about">About</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="/" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Options
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'users:signin' %}">SignIn</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:signout' %}">SignOut</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    {% block body %} {% endblock %}



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/class_details.html
{% extends 'sidebar.html' %}
{% load static %}


{% block title %} Class Details {% endblock %}

{% block content %}

<div class="col-9">

    <!-- {{course}} -->
    <div class="container-fluid border my-3">

        <table id="student_list">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">COURSE</th>
                    <th scope="col">SEMESTER</th>
                    <th scope="col">SUBJECT</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>

{% endblock %}


{% block script %}
<script>
    $(document).ready(function () {
        let table = $('#student_list').DataTable({
            "ajax": {
                "processing": true,
                "url": "{% url 'tau:list_classes' id %}",
                "dataSrc": "",
            },
            "columns": [
                {
                    "data": "id",
                    "render": function (data, type, row, meta) {
                        let id = row.id  
                        let a = "<a href='{% url 'tau:class_details' id %}' style='color:blue;'>" + id + '</a>';
                        return a;
                    }
                },
                { "data": "course" },
                { "data": "semester" },
                { "data": "subject" },
            ],
        });

    });


</script>
{% endblock %}

templates/class_history.html
{% extends 'sidebar.html' %}
{% load static %}


{% block title %} Class History {% endblock %}

{% block content %}

<div class="col-9">

    <div class="container-fluid border my-3">

        <table id="student_list">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">COURSE</th>
                    <th scope="col">SEMESTER</th>
                    <th scope="col">SUBJECT</th>
                    <th scope="col">DATE</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>


{% endblock %}


{% block script %}
<script>

    $(document).ready(function () {
        let table = $('#student_list').DataTable({
            "ajax": {
                "processing": true,
                "url": "{% url 'tau:list_classes' id %}",
                "dataSrc": "",
            },
            "columns": [
                { "data": "id" },
                { "data": "course" },
                { "data": "semester" },
                { "data": "subject" },
                { "data": "date" },
            ],
        });

    });


</script>
{% endblock %}

templates/create.html
{% extends 'sidebar.html' %}

{% block title %} Class {% endblock %}

{% block content %}

<div class="col-9">
    <div class="container d-flex border my-3">

        <div class="container bg-transparent w-75" id="editing-form">

            <h2><strong>ENTER CLASS DETAILS</strong></h2>

            <form id="post-form" action="{% url 'tau:create' id %}" name="form" method="POST" onsubmit="return validate()">
                {% csrf_token %}

                <div>
                    <label for="subject" class="form-label">Subject</label>
                    <input type="text" class="form-control data-input" id="subject" name="subject" />
                </div>

                <div>
                    <label for="course" class="form-label">Course</label>
                    <input type="text" class="form-control data-input" id="course" name="course" />
                </div>

                <div>
                    <label for="semester" class="form-label">Semester</label>
                    <input type="text" class="form-control data-input" id="semester" name="semester" />
                </div>

                <button type="submit" class="btn btn-success my-4 mx-2 py-1" id="update_button"
                    name="update_button">Create Class</button>

            </form>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}

<script>

    function validate() {
        subject = document.getElementById('subject').value;
        course = document.getElementById('course').value;
        semester = document.getElementById('semester').value;

        if (
            subject.length == 0 &&
            course.length == 0 &&
            semester.length == 0
        ) {
            alert("You cannot create a class without submitting the necessary details!");
            return false;
        }
    }

</script>

{% endblock %}

templates/display.html
{% extends 'sidebar.html' %}
{% load static %}


{% block title %} Class History {% endblock %}

{% block content %}

<div class="container-fluid border col-9">

    <div class="container-fluid">
        <h3>ATTENDANCE SINCE {{class_details.start_date}}</h3>
        <h4>SUBJECT: {{class_details.subject}}</h4>
        <h4>COURSE: {{class_details.course}}</h4>
        <h4>SEMESTER: {{class_details.semester}}</h4>
        <h4>TOTAL NUMBER OF CLASSES TAKEN: {{total_classes}}</h4>
    </div>

    <div class="container-fluid border my-3">
        <table id="student_list">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>ROLL NUMBER</th>
                    <th>FIRST NAME</th>
                    <th>LAST NAME</th>
                    <th>CLASSES ATTENDED</th>
                    <th>PERCENTAGE</th>
                </tr>
            </thead>
            <tbody>
                {% for a in attendance %}
                <tr>
                    <td>
                        {{ a.id }}
                    </td>
                    <td>
                        {{ a.roll }}
                    </td>
                    <td>
                        {{ a.firstname }}
                    </td>
                    <td>
                        {{ a.lastname }}
                    </td>
                    <td>
                        {{ a.classes_attended }}
                    </td>
                    <td>
                        {{ a.percentage }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
</div>


{% endblock %}


{% block script %}
<script>
</script>
{% endblock %}

templates/editprofile.html
{% extends 'sidebar.html' %}

{% block title %} Edit {% endblock %}

{% block content %}

<div class="col-9">
    <div class="container d-flex border my-3">

        <div class="container bg-transparent w-75" id="editing-form">

            <h2><strong>Edit Profile</strong></h2>

            <form id="post-form" action="{% url 'users:edit_profile' id %}" method="POST" onsubmit="return validate()">
                {% csrf_token %}

                <div>
                    <label for="firstname" class="form-label">First Name</label>
                    <input type="text" class="form-control data-input" id="firstname" name="firstname" />
                </div>

                <div>
                    <label for="lastname" class="form-label">Last Name</label>
                    <input type="text" class="form-control data-input" id="lastname" name="lastname" />
                </div>


                <div>
                    <label for="email" class="form-label">Email address</label>
                    <input type="email" class="form-control data-input" id="email" name="email" />
                </div>

                <div>
                    <label for="subject1" class="form-label">Subject 1</label>
                    <input type="text" class="form-control data-input" id="subject1" name="subject1" />
                </div>

                <div>
                    <label for="subject2" class="form-label">Subject 2</label>
                    <input type="text" class="form-control data-input" id="subject2" name="subject2" />
                </div>

                <div>
                    <label for="subject3" class="form-label">Subject 3</label>
                    <input type="text" class="form-control data-input" id="subject3" name="subject3" />
                </div>

                <div>
                    <label for="subject4" class="form-label">Subject 4</label>
                    <input type="text" class="form-control data-input" id="subject4" name="subject4" />
                </div>

                <div>
                    <label for="department" class="form-label">Department</label>
                    <input type="text" class="form-control data-input" id="department" name="department" />
                </div>

                <div>
                    <label for="college" class="form-label">College</label>
                    <input type="text" class="form-control data-input" id="college" name="college" />
                </div>

                <div>
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control data-input" id="password" name="password" />
                </div>


                <div>
                    <label for="cpassword" class="form-label">Confirm Password</label>
                    <input type="password" class="form-control data-input" id="cpassword" name="cpassword" />
                </div>

                <button type="submit" class="btn btn-success my-4 mx-2 py-1" id="update_button"
                    name="update_button">Save Changes</button>

            </form>
        </div>
    </div>
</div>


{% endblock %}

{% block script %}

<script>

    function validate() {
        firstname = document.getElementById('firstname').value;
        lastname = document.getElementById('lastname').value;
        email = document.getElementById('email').value;
        subject1 = document.getElementById('subject1').value;
        subject2 = document.getElementById('subject2').value;
        subject3 = document.getElementById('subject3').value;
        subject4 = document.getElementById('subject4').value;
        department = document.getElementById('department').value;
        college = document.getElementById('college').value;
        password = document.getElementById('password').value;
        cpassword = document.getElementById('cpassword').value;


        if (
            firstname.length == 0 &&
            lastname.length == 0 &&
            email.length == 0 &&
            subject1.length == 0 &&
            subject2.length == 0 &&
            subject3.length == 0 &&
            subject4.length == 0 &&
            department.length == 0 &&
            college.length == 0 &&
            password.length == 0 &&
            cpassword.length == 0) {
            alert("You cannot submit a form with all fields empty!");
            return false;
        }


        if (password === cpassword) {
            return true;
        }
        else {
            alert("Password and confirm password fields should match!")
            return false;
        }
    }

</script>

{% endblock %}

templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error!</title>
</head>
<body>
    <h1>Internal Server Error!</h1>
</body>
</html>

templates/index.html
{% extends 'basic.html' %}

{% block title %} Home {% endblock %}

{% block body %}

<h1>This is Home Page</h1> 


{{success|json_script:"success"}}
{{message|json_script:"message"}}


<script>

    const success = JSON.parse(document.getElementById('success').textContent);
    const message = JSON.parse(document.getElementById('message').textContent);

    console.log(success)
    console.log(message)

    if (success === false && message === 'already signed-out') {
        alert('You have already signed out!')
    }

</script>
{% endblock %}

templates/list.html
{% extends 'sidebar.html' %}
{% load static %}


{% block title %} List {% endblock %}

{% block content %}

<div class="col-9">

    <div class="container-fluid border my-3">

        <table id="student_list">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">ROLL</th>
                    <th scope="col">FIRST NAME</th>
                    <th scope="col">LAST NAME</th>
                    <th scope="col">EMAIL</th>
                    <th scope="col">COURSE</th>
                    <th scope="col">SEMESTER</th>
                    <th scope="col">DEPT. ID</th>
                    <th scope="col">COLLEGE</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>

{% endblock %}


{% block script %}
<script>
    $(document).ready(function () {
        let table = $('#student_list').DataTable({
            "ajax": {
                "processing": true,
                "url": "{% url 'tau:list_data' id %}",
                "dataSrc": "",
            },
            "columns": [
                { "data": "id" },
                { "data": "roll" },
                { "data": "firstname" },
                { "data": "lastname" },
                { "data": "email" },
                { "data": "course" },
                { "data": "semester" },
                { "data": "department" },
                { "data": "college" },
            ],
        });
    });

</script>
{% endblock %}

templates/profile.html
{% extends 'sidebar.html' %}
{% load static %}


{% block content %}

<div class="col-9" id="profile-content">

    <div class="row data-row mx-1 my-2">

        <span>Institution: <strong>{{college}}</strong></span>
        <br>
        <span>Department: <strong>{{department}}</strong></span>

    </div>
    
    <br>

    <div class="row data-row mx-1 my-2">
        <div class="col-6">
            <p>First Name: <strong>{{firstname}}</strong></p>
            <p>Last Name: <strong>{{lastname}}</strong></p>
            <p>Email: <strong>{{email}}</strong></p>
        </div>

        <div class="col-6">
            <p>Subject 1: <strong>{{subject1}}</strong></p>
            <p>Subject 2: <strong>{{subject2}}</strong></p>
            <p>Subject 3: <strong>{{subject3}}</strong></p>
            <p>Subject 4: <strong>{{subject4}}</strong></p>
        </div>
    </div>

    
    <div class="row data-row mx-1 my-2">
        <form id="post-form" action="{% url 'tau:display' id %}" method="POST" onsubmit="return validate()">
            {% csrf_token %}

            <div>
                <label for="subject" class="form-label">Subject</label>
                <input type="text" class="form-control data-input" id="subject" name="subject" required/>
            </div>

            <div>
                <label for="course" class="form-label">Course</label>
                <input type="text" class="form-control data-input" id="course" name="course" required/>
            </div>

            <div>
                <label for="semester" class="form-label">Semester</label>
                <input type="number" class="form-control data-input" id="semester" name="semester" required/>
            </div>

            <div>
                <label for="start_date" class="form-label">Attendance From:</label>
                <input type="date" class="form-control data-input" id="start_date" name="start_date" required/>
            </div>

            <button type="submit" class="btn btn-success my-4 mx-2 py-1" id="display_button"
                name="display_button">Display Attendance</button>

        </form>
    </div>

</div>

{% endblock %}

templates/sidebar.html
{% extends 'basic.html' %}
{% load static %}

{% block title %} Profile {% endblock %}

{% block body %}

<div>
        <div class="row">
                <div class="col-2 border mx-2" id="sidebar">

                        <h3 class="text-center my-3">FROAS</h3>
                        <div class="my-4">
                                <a href="{% url 'users:get_profile' id %}">
                                        <div class="py-2 px-2 my-2 option">Profile</div>
                                </a>

                                <a href="{% url 'users:edit_profile' id %}">
                                        <div class="py-2 px-2 my-2 option">Edit Profile</div>
                                </a>
                                <a href="{% url 'tau:list' id %}">
                                        <div class="py-2 px-2 my-2 option">List Students</div>
                                </a>
                                <a href="{% url 'tau:upload' id %}">
                                        <div class="py-2 px-2 my-2 option">Upload Samples</div>
                                </a>
                                <a href="{% url 'tau:create' id %}">
                                        <div class="py-2 px-2 my-2 option">Create Class</div>
                                </a>
                                <a href="{% url 'tau:class_history' id %}">
                                        <div class="py-2 px-2 my-2 option">Class History</div>
                                </a>
                        </div>
                </div>

                {% block content %}{% endblock %}


        </div>


</div>
{% block script %} {% endblock %}

{% endblock %}

templates/signin.html
{% extends 'basic.html' %}

{% block title %} SignIn - FROAS {% endblock %}

{% block body %}

<div>
    <div class="container d-flex w-50 border my-3">

        <div class="container bg-transparent w-100" id="signup-form">

            <h2><strong>Sign In</strong></h2>

            <form id="post-form" action="{% url 'users:signin' %}" method="POST" onsubmit="return validate()">
                {% csrf_token %}

                <div>
                    <label for="id" class="form-label">User ID</label>
                    <input type="text" class="form-control data-input" id="id" name="id" required />
                </div>

                <div>
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control data-input" id="password" name="password" required />
                </div>

                <div id="error"></div>

                <button type="submit" class="btn btn-success my-4 mx-2 py-1" id="signin_button"
                    name="signin_button">Sign In</button>

            </form>
        </div>
    </div>



    {{success|json_script:"success"}}
    {{message|json_script:"message"}}


</div>

<script>
    const success = JSON.parse(document.getElementById('success').textContent);
    const message = JSON.parse(document.getElementById('message').textContent);

    console.log(success)
    console.log(message)

    if(success == false && message === 'invalid credentials') {
        error = document.getElementById('error');
        error.innerHTML = 'Login with proper credentials!';
        error.style.color = 'red';
    }

</script>

{% endblock %}

templates/upload.html
{% extends 'sidebar.html' %}

{% block title %} Upload {% endblock %}

{% block content %}


<div class="col-9">
    <div class="conatainer border my-3">

        <div class="container w-75">

            <h2>Upload samples here</h2>

            <form action="{% url 'tau:upload' id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div>
                    <label for="student_id" class="form-label">Student_ID</label>
                    <input type="number" class="form-control data-input" id="student_id" name="student_id" required>
                </div>


                <div>
                    <label for="files" class="form-label">Sample Photos</label>
                    <input type="file" class="form-control data-input" id="files" name="files" required multiple>
                </div>


                <button type="submit" class="btn btn-success my-4 mx-2 py-1" id="upload_samples"
                    name="upload_samples">Upload Samples</button>

            </form>
        </div>
    </div>
</div>



{{success|json_script:"success"}}
{{message|json_script:"message"}}

{% endblock %}

{% block script %}

<script>

    const success = JSON.parse(document.getElementById('success').textContent);
    const message = JSON.parse(document.getElementById('message').textContent);

    console.log(success)
    console.log(message)

    if (success === false && message === 'already signed-out') {
        alert('You have already signed out!')
    }

</script>

{% endblock %}